
package bc.intra.middleware.api.services.pubsub.push;

import javax.xml.ws.WebFault;
import bc.intra.middleware.api.schema.fault.FaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PublishFault", targetNamespace = "http://middleware.intra.bc/api/services/pubsub/push")
public class PublishFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PublishFaultMessage(String message, FaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PublishFaultMessage(String message, FaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: bc.intra.middleware.api.schema.fault.FaultType
     */
    public FaultType getFaultInfo() {
        return faultInfo;
    }

}
