
package bc.intra.middleware.api.services.pubsub.push;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "publish_portype", targetNamespace = "http://middleware.intra.bc/api/services/pubsub/push")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    bc.intra.middleware.api.schema.fault.ObjectFactory.class,
    bc.intra.middleware.api.schema.pubsub.ObjectFactory.class,
    bc.intra.middleware.api.services.pubsub.push.ObjectFactory.class
})
public interface PublishPortype {


    /**
     * 
     * @param parameters
     * @return
     *     returns bc.intra.middleware.api.services.pubsub.push.PublishResponseType
     * @throws PublishFaultMessage
     */
    @WebMethod(operationName = "Publish", action = "http://www.proximus.com/middleware/services/pubsub/Publish")
    @WebResult(name = "PublishResponse", targetNamespace = "http://middleware.intra.bc/api/services/pubsub/push", partName = "parameters")
    public PublishResponseType publish(
        @WebParam(name = "PublishRequest", targetNamespace = "http://middleware.intra.bc/api/services/pubsub/push", partName = "parameters")
        PublishRequestType parameters)
        throws PublishFaultMessage
    ;

}
