//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.20 at 03:55:55 PM CET 
//


package bgc.billing.audit4bil.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bgc.billing.audit4bil package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PublishFault_QNAME = new QName("http://middleware.intra.bc/api/services/pubsub", "PublishFault");
    private final static QName _PublishRequest_QNAME = new QName("http://middleware.intra.bc/api/services/pubsub", "PublishRequest");
    private final static QName _PublishResponse_QNAME = new QName("http://middleware.intra.bc/api/services/pubsub", "PublishResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bgc.billing.audit4bil
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KeyValueType }
     * 
     */
    public KeyValueType createKeyValueType() {
        return new KeyValueType();
    }

    /**
     * Create an instance of {@link FaultType }
     * 
     */
    public FaultType createFaultType() {
        return new FaultType();
    }

    /**
     * Create an instance of {@link PublishResponseType }
     * 
     */
    public PublishResponseType createPublishResponseType() {
        return new PublishResponseType();
    }

    /**
     * Create an instance of {@link PublishMessageType }
     * 
     */
    public PublishMessageType createPublishMessageType() {
        return new PublishMessageType();
    }

    /**
     * Create an instance of {@link SubscriptionType }
     * 
     */
    public SubscriptionType createSubscriptionType() {
        return new SubscriptionType();
    }

    /**
     * Create an instance of {@link MessageIdType }
     * 
     */
    public MessageIdType createMessageIdType() {
        return new MessageIdType();
    }

    /**
     * Create an instance of {@link FaultDetailsType }
     * 
     */
    public FaultDetailsType createFaultDetailsType() {
        return new FaultDetailsType();
    }

    /**
     * Create an instance of {@link ReceivedMessageType }
     * 
     */
    public ReceivedMessageType createReceivedMessageType() {
        return new ReceivedMessageType();
    }

    /**
     * Create an instance of {@link SubscriptionMessageType }
     * 
     */
    public SubscriptionMessageType createSubscriptionMessageType() {
        return new SubscriptionMessageType();
    }

    /**
     * Create an instance of {@link PublishRequestType }
     * 
     */
    public PublishRequestType createPublishRequestType() {
        return new PublishRequestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://middleware.intra.bc/api/services/pubsub", name = "PublishFault")
    public JAXBElement<FaultType> createPublishFault(FaultType value) {
        return new JAXBElement<FaultType>(_PublishFault_QNAME, FaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublishRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://middleware.intra.bc/api/services/pubsub", name = "PublishRequest")
    public JAXBElement<PublishRequestType> createPublishRequest(PublishRequestType value) {
        return new JAXBElement<PublishRequestType>(_PublishRequest_QNAME, PublishRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublishResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://middleware.intra.bc/api/services/pubsub", name = "PublishResponse")
    public JAXBElement<PublishResponseType> createPublishResponse(PublishResponseType value) {
        return new JAXBElement<PublishResponseType>(_PublishResponse_QNAME, PublishResponseType.class, null, value);
    }

}
