//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.20 at 03:55:55 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://middleware.intra.bc/api/schema/pubsub")
package bgc.billing.audit4bil.xsd;
